### ISSUE TITLE
Need some extra explanation

### ISSUE THREAD

**Issue by matzeema** [SunnyWolf/goldenmotor_protocol#3]
In the first place - thank you so much for this repo! Finding out all these informations has probably taken a while. Thanks you made it public.

But even with your explanations I have still some trouble to get the communication working. I already made it to send the echo command to the controller and got an answer back, so my problem is more of to understanding the protocol right.

If I want to get the state of the controller and I am sending this command:

|  START |  CMD   | LENGTH |  CRC   |
|:------:|:------:|:------:|:------:|
|  0x66  |  0x46  |  0x00  |  0xAC  |

I have calculated the CMD field by summing `0x42` (LCD info command) and `0x04` (offset of the state parameter). Because there is no payload (there isn't, is there?) I set the length to `0x00` and finally calculated the CRC value. Have I understood this method right?

The value I get back is:
Decimal : `102 70 6 0 0 255 0 0 3 180`, Hexa: `66 46 06 00 00 FF 00 00 03 B4`
So whats the state value here and want does the other values mean?

Thanks in advance!

**Comment by SunnyWolf** [comment]
Hello.
If you want to get a state from a controller, you need to send a 0x42
command with zero length.
In response you should get some similar data:
STARTCMDLENGTHBAT
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_BAT>
CUROLD
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_CUROLD>
TSNS
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_TSNS>
STATE
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_STATE>
USER
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_USER>
VOL
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_VOL>
CUR
<https://github.com/SunnyWolf/goldenmotor_protocol/blob/master/commands.md#cmd42_CUR>
0x66 0x42 1 byte 1 byte 1 byte 2 bytes 1 byte 2 bytes 2 bytes 2 bytes
 You need 8-th byte of this message that represents the state of the
controller.

вс, 20 сент. 2020 г. в 14:49, matzesoft <notifications@github.com>:

**Comment by matzeema** [comment]
Thanks! Finally got it. I was kinda confused with the table at the bottom and the offset value of every parameter.
